name       : seexpr
version    : 2.11
release    : 2
source     :
    - https://github.com/wdas/SeExpr/archive/v2.11.tar.gz : bf4a498f86aa3fc19aad3d7384de11d5df76f7f71587c9bd789f5e50f8090e1a
license    : Apache-2.0
component  : programming
summary    : Simple expression language
description: |
    Simple expression language
libsplit   : no
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpng)
    - pkgconfig(QtCore)
    - python-qt4
build      : |
    export prefix=/usr
    %make
install    : |-
    export prefix=/usr
    %make_install
    rm -r $installdir/usr/share/test
    rm $installdir/usr/lib64/libSeExpr.a
